server:
  port: 8761

spring:
  application:
    name: micro-registry

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: ${EUREKA_REGISTER:false}
    fetch-registry: ${EUREKA_FETCH:false}
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

